### ISSUE TITLE
AttributeError: 'module' object has no attribute 'io'

### ISSUE THREAD

**Issue by aquibjaved** [nitish11/GenderRecognition#2]
I am trying the code **gender_demo_caffe.py** 
I am getting an error: `a = caffe.io.caffe_pb2.BlobProto.FromString(proto_data)
AttributeError: 'module' object has no attribute 'io'
`

How to solve it, I've tried to search but did not get any answer.

**Comment by nitish11** [comment]
The issue lies in the installation of caffe.

Install Caffe latest build from github [link](https://github.com/BVLC/caffe)

Also, upgrade the dependencies by following command

```
cd $CAFFE_ROOT/python
for req in $(cat requirements.txt); do pip install $req --upgrade; done
```

**Comment by aquibjaved** [comment]
Hi @nitish11 
I did the installation again from the scratch but again I am getting the same error.

**Comment by nitish11** [comment]
@aquibjaved : Could you please comment and close the issue, how did you fix it?

**Comment by aquibjaved** [comment]
I did the installation from scratch but before that deleted all files related to caffe. and I also installed CUDA but I am not sure that it helps me or not. Now I am able to use the caffe there's no problem even my code gender_recognition is working.
Thank you @nitish11
